apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/knowledge-things/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      valueFiles:
        - values.yaml
      # valuesObject:
      #   fullnameOverride: guestbook-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: default