apiVersion: v1
data:
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCT1VGUk5vcWlXT3MybWROUnBkOENiN0EyTXMxVkQ3dXRlK0xHUU5GZDYwZ0FBQUtDamZkaFpvMzNZCldRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQk9VRlJOb3FpV09zMm1kTlJwZDhDYjdBMk1zMVZEN3V0ZStMR1FORmQ2MGcKQUFBRUJycnZFRVNsTFRMZnh1cFNWSlppT0txRFlON2xacTRqdU4xVHdVZmdVNGgwNVFWRTJpcUpZNnphWjAxR2wzd0p2cwpEWXl6VlVQdTYxNzRzWkEwVjNyU0FBQUFGRWRsYm1WeVlYUmxaQ0JDZVNCVVpYSnRhWFZ6QVFJREJBVUdCd2dKCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQ==
  type: Z2l0
  url: Z2l0QGdpdGh1Yi5jb206a25vd2xlZGdlLXRoaW5ncy9hcmdvY2QtY291cnNlLXByaXZhdGUtcmVwby1kZW1vLmdpdA==
kind: Secret
metadata:
  name: private-repo-ssh
  namespace: argocd
