## @param customName allows to set a custom resource name for the deployment and service
##        Default to {{ .Release.Name }}-{{ .Chart.Name }}
customName : "my-custom-release"
# Replica count
# Image, both name and tag
# Service type and port
environment: production

## #param replicaCount Number of Nginx replicas to deploy
replicaCount: 3

## Settings for the Nginx image
## @param image.name The name of the Nginx image
## @param image.tag The tag of the Nginx image
image:
  name: nginx
  tag: "1.27.0"

## Settings for the Nginx image
##
## @param securityContext.enabled Whether to enable security context for the Nginx container
## @param securityContext.runAsUser The user ID to run the Nginx container as
## @param securityContext.fsGroup The group ID to run the Nginx container as
securityContext:
  enabled: true
  runAsUser: 1000
  fsGroup: 2000

## Nginx container settings
##
## @param containerPort The port of the Nginx container
containerPorts:
  http: 80

## Settings for the Nginx service
## Service settings 
##
## @param services["*""].type The type of the Nginx service  
## @param services["*""].port The port of the Nginx service
services:
  svc1:
    type: ClusterIP
    port: 80
  svc2:
    type: NodePort
    port: 30007
